spring:
  application:
    name: mercado-livro
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mercado_livro_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: update

server:
  port: 8080