spring:
  application:
    name: mercado-livro
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
  flyway:
    enabled: false
server:
  port: 8080