spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: mercado-livro
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
  flyway:
    enabled: false
server:
  port: 8080

jwt:
  expiration: 999999
  secret: 04dc701e-cf23-4388-83f0-4c15aa68d911

